version: ''

volumes:
  my-kafka-1:
  my-kafka-2:
services:
  my-kafka-1:
    image: 'bitnami/kafka:3.8.0'
    container_name: my-kafka-1
    ports:
      - '10092:10092'
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:10092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://my-kafka-1:9092,EXTERNAL://localhost:10092
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@my-kafka-1:9093,2@my-kafka-2:9093'
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
#    volumes:
#      - my-kafka-1:/bitnami/kafka
  my-kafka-2:
    image: 'bitnami/kafka:3.8.0'
    container_name: my-kafka-2
    ports:
      - '10093:10093'
    environment:
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: 'broker,controller'
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:10093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://my-kafka-2:9092,EXTERNAL://localhost:10093
      KAFKA_CFG_BROKER_ID: 2
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: '1@my-kafka-1:9093,2@my-kafka-2:9093'
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_KRAFT_CLUSTER_ID: 5L6g3nShT-eMCtK--X86sw
#    volumes:
#      - my-kafka-2:/bitnami/kafka
  kafka-ui:
    container_name: my-kafka-ui
    image: 'provectuslabs/kafka-ui:latest'
    depends_on:
      - my-kafka-1
      - my-kafka-2
    ports:
      - "8989:8080"
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: 'my-kafka-1:9092,my-kafka-2:9092'
      KAFKA_CLUSTERS_0_NAME: my-kafka