server:
  port: 8080

spring:
  application:
    name: open-chat
  profiles:
    active: local
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages/messages
    encoding: UTF-8
    cacheDuration: 3
    alwaysUseMessageFormat: true
    useCodeAsDefaultMessage: true
    fallbackToSystemLocale: true
  kafka:
    consumer:
      bootstrap-servers:
      group-id: chat
    producer:
      bootstrap-servers:

translation:
  server:
    url: