server:
  port: 8080

spring:
  application:
    name: open-chat
  profiles:
    active: local
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  messages:
    basename: messages/messages
    encoding: UTF-8
    cacheDuration: 3
    alwaysUseMessageFormat: true
    useCodeAsDefaultMessage: true
    fallbackToSystemLocale: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer